import type { Metadata } from "next";
import "../globals.css";
import ThemeProviderComponent from "@/provider/themeProvider";
import AppContextProvider from "@/provider/appContext";
import Paper from "@mui/material/Paper";
import ApolloManager from "@/graphql/client";
import { ReactNode } from "react";
import { NextIntlClientProvider } from "next-intl"
import { QueryClientProvider } from "@/provider/query-client";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
params
}: {
  children: ReactNode;
 params: Promise<{ lang: "en" | "fa" }>;

}) {
  const locale =  (await params).lang
 const messages = (await import(`../../../messages/${locale}.json`)).default
  return (
    <html  lang={locale}
      dir={locale === "en" ? "ltr" : "rtl"}>
      <body>
        <QueryClientProvider>
          <NextIntlClientProvider  locale={locale} messages={messages}  >
          <AppContextProvider>
            <ThemeProviderComponent>
              <Paper sx={{minHeight:"100vh"}}>{children}</Paper>
            </ThemeProviderComponent>
          </AppContextProvider>
          </NextIntlClientProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
