
export const RECEIVE_LIST_QUERY_KEY = "getReceiveList"
export const PAY_OF_LIST_QUERY_KEY = "getPayOfList"
export const SELLS_BILL_LIST_QUERY_KEY = "getSellsBillList"
export const SELLS_BILL_BY_ID_QUERY_KEY = "getSellsBillById"
export const GET_CONSUMPTION_LIST_QUERY_KEY = "getConsumptionList"
export const GET_CONSUMPTION_TYPE_LIST_QUERY_KEY = "getConsumptionTypeList"
export const GET_EXTERNAL_INCOME_LIST_QUERY_KEY = "getExternalIncomeList"
export const GET_EXTERNAL_INCOME_TYPE_LIST_QUERY_KEY = "getExternalIncomeTypeList"
export const GET_BANK_LIST_QUERY_KEY = "getBankList"
export const GET_SAFE_LIST_QUERY_KEY = "getSafeList" 
export const GET_CUSTOMER_LIST_QUERY_KEY = "getCustomerList" 
export const GET_EMPLOYEE_LIST_QUERY_KEY = "getEmployeeList" 