import type { Metadata } from "next";
import "./globals.css";
import ThemeProviderComponent from "@/provider/themeProvider";
import AppContextProvider from "@/provider/appContext";
import Paper from "@mui/material/Paper";
import ApolloManager from "@/graphql/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ApolloManager>
          <AppContextProvider>
            <ThemeProviderComponent>
              <Paper sx={{ height: "100vh" }}>{children}</Paper>
            </ThemeProviderComponent>
          </AppContextProvider>
        </ApolloManager>
      </body>
    </html>
  );
}
